spring.application.name=WeatherApp
//weather.api.key=0ccc7fcb357c461a908134845262605
weather.api.key=51c08b4d002a46c398353605260106
weather.api.url=http://api.weatherapi.com/v1/current.json
weather.api.forecast.url=http://api.weatherapi.com/v1/forecast.json